package org.gcreator.runero.script;

@Deprecated
public class GameMakerLibrary {
    // move
    public static final int ACTION_MOVE = 101;
    public static final int SET_MOTION = 102;
    public static final int MOVE_POINT = 105;
    public static final int SET_HSPEED = 103;
    public static final int SET_VSPEED = 104;
    public static final int SET_GRAVITY = 107;
    public static final int REVERSE_XDIR = 113;
    public static final int REVERSE_YDIR = 114;
    public static final int SET_FRICTION = 108;
    public static final int MOVE_TO = 109;
    public static final int MOVE_START = 110;
    public static final int MOVE_RANDOM = 111;
    public static final int SNAP = 117;
    public static final int WRAP = 112;
    public static final int MOVE_CONTACT = 116;
    public static final int BOUNCE = 115;
    public static final int PATH = 119;
    public static final int PATH_END = 124;
    public static final int PATH_POSITION = 122;
    public static final int PATH_SPEED = 123;
    public static final int STEP_LINEAR = 120;
    public static final int STEP_POTENTIAL = 121;
    // main1
    public static final int CREATE_OBJECT = 201;
    public static final int CREATE_OBJECT_MOTION = 206;
    public static final int CREATE_OBJECT_RANDOM = 207;
    public static final int CHANGE_OBJECT = 202;
    public static final int KILL_OBJECT = 203;
    public static final int KILL_POSITION = 204;
    public static final int SET_SPRITE = 541;
    public static final int TRANSFORM_SPRITE = 542;
    public static final int COLOR_SPRITE = 543;
    public static final int SET_SPRITE_OLD = 205; // DEPRECATED
    public static final int BEGIN_SOUND = 211;
    public static final int END_SOUND = 212;
    public static final int IF_SOUND = 213;
    public static final int PREVIOUS_ROOM = 221;
    public static final int NEXT_ROOM = 222;
    public static final int CURRENT_ROOM = 223;
    public static final int ANOTHER_ROOM = 224;
    public static final int IF_PREVIOUS_ROOM = 225;
    public static final int IF_NEXT_ROOM = 226;
    // main2
    public static final int SET_ALARM = 301;
    public static final int SLEEP = 302;
    public static final int SET_TIMELINE = 303;
    public static final int POSITION_TIMELINE = 304;
    public static final int MESSAGE = 321;
    public static final int SHOW_INFO = 322;
    public static final int SHOW_VIDEO = 323;
    public static final int RESTART_GAME = 331;
    public static final int END_GAME = 332;
    public static final int SAVE_GAME = 333;
    public static final int LOAD_GAME = 334;
    public static final int REPLACE_SPRITE = 803;
    public static final int REPLACE_SOUND = 804;
    public static final int REPLACE_BACKGROUND = 805;
    // control
    public static final int IF_EMPTY = 401;
    public static final int IF_COLLISION = 402;
    public static final int IF_OBJECT = 403;
    public static final int IF_NUMBER = 404;
    public static final int IF_DICE = 405;
    public static final int IF_QUESTION = 407;
    public static final int IF = 408;
    public static final int IF_MOUSE = 409;
    public static final int IF_ALIGNED = 410;
    public static final int START_BLOCK = 422;
    public static final int ELSE = 421;
    public static final int EXIT = 425;
    public static final int END_BLOCK = 424;
    public static final int REPEAT = 423;
    public static final int INHERITED = 604;
    public static final int CODE = 603;
    public static final int EXECUTE_SCRIPT = 601;
    public static final int COMMENT = 605;
    public static final int VARIABLE = 611;
    public static final int IF_VARIABLE = 612;
    public static final int DRAW_VARIABLE = 613;
    // score
    public static final int SET_SCORE = 701;
    public static final int IF_SCORE = 702;
    public static final int DRAW_SCORE = 703;
    public static final int HIGHSCORE_SHOW = 709;
    public static final int HIGHSCORE_CLEAR = 707;
    public static final int SET_LIFE = 711;
    public static final int IF_LIFE = 712;
    public static final int DRAW_LIFE = 713;
    public static final int DRAW_LIFE_IMAGES = 714;
    public static final int SET_HEALTH = 721;
    public static final int IF_HEALTH = 722;
    public static final int DRAW_HEALTH = 723;
    public static final int SET_CAPTION = 731;
    // extra i.e. never going to be implemented
    public static final int PART_SYST_CREATE = 820;
    public static final int PART_SYST_DESTROY = 821;
    public static final int PART_SYST_CLEAR = 822;
    public static final int PART_TYPE_CREATE_OLD = 825; // DEPRECATED
    public static final int PART_TYPE_CREATE = 823;
    public static final int PART_TYPE_COLOR = 824;
    public static final int PART_TYPE_LIFE = 826;
    public static final int PART_TYPE_SPEED = 827;
    public static final int PART_TYPE_GRAVITY = 828;
    public static final int PART_TYPE_SECONDARY = 829;
    public static final int PART_EMIT_CREATE = 831;
    public static final int PART_EMIT_DESTROY = 832;
    public static final int PART_EMIT_BURST = 833;
    public static final int PART_EMIT_STREAM = 834;
    public static final int CD_PLAY = 808;
    public static final int CD_STOP = 809;
    public static final int CD_PAUSE = 810;
    public static final int CD_RESUME = 811;
    public static final int CD_IF_EXISTS = 812;
    public static final int CD_IF_PLAYING = 813;
    public static final int SET_MOUSE = 801;
    public static final int OPEN_WEBPAGE = 807;
    //draw
    public static final int DRAW_SPRITE = 501;
    public static final int DRAW_BACKGROUND = 502;
    public static final int DRAW_TEXT = 514;
    public static final int DRAW_TEXT_SCALED = 519;
    public static final int DRAW_RECTANGLE = 511;
    public static final int DRAW_GRADIENT_HOR = 516;
    public static final int DRAW_GRADIENT_VERT = 517;
    public static final int DRAW_ELLIPSE = 512;
    public static final int DRAW_ELLIPSE_GRADIENT = 518;
    public static final int DRAW_LINE = 513;
    public static final int DRAW_ARROW = 515;
    public static final int SET_COLOR = 524;
    public static final int SET_FONT = 526;
    public static final int FULLSCREEN = 531;
    public static final int TAKE_SNAPSHOT = 802;
    public static final int EFFECT = 532;
}
